### ISSUE TITLE
[Non-Technical]: Website Design

### ISSUE THREAD

**Issue by wikipop** [EKK-Ingarden/LandsatWebTracker#20]
### Task description

[Designfile](https://www.figma.com/design/fvXEietYlF2Q5vGPDJCnQd/Nasa-2024-design?node-id=0-1&t=TPAixU6PvhQx0KaQ-1) link to org is on discord, text me if u cant join. 

Design must contain following pages:
- [ ] Sign in/up page - I leave how it should look to your imagination
- [ ] Application form with map component (mockup look below)
- [ ] Reports list page (mockup look below)

These are less important are can be generic if applicable
- [ ] About us
- [ ] Instruction page
- [ ] Profile settings

![Form Mockup](https://github.com/user-attachments/assets/61ce3a59-4e08-44d7-bd15-8af14bc6570c)
![Reports Mockup](https://github.com/user-attachments/assets/74e54f00-eebd-4356-99aa-2ec1d76fba88)
